<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // yield 就是返回了迭代器对象(包含next与return函数)!
    // 所以能将生成器作为迭代器使用
    class max{
      constructor(name){
        this.name=[name,'chloe','rachel']
      }
      *[Symbol.iterator](){
        yield this.name
      }
    }
    let js=new max('js')
    for (let a of js){
      console.log(a);
    }
    // 生成器实现的迭代器对象有三个终止的方法,next return throw
    function * chloe(){
      for (const x of [1,2,3]){
        // 当外部终止掉生成器后,这里不返回值
        yield x;
      }
    }
    let a=chloe();
    console.log(a.next,a.return,a.throw);//三个终止方法
    for (let x of a){
      if(x>1){
        // 数组中的3与return的参数4都不会被打印出来,
        a.return(4)
      }
      console.log(x);
    }
    // thorw停止生成器
    function* rachel(){
      for(const x of [1,3,5]){
        // 如果在生成器内部进行trycatch,则生成器不会被关闭
        try{
          yield x;
        }catch(err){
          console.log(err);
        }
      }
    }
    let b=rachel();
    // try {
    //   b.throw('出错啦!')//暂停生成器并抛出错误,在生成器外部的trycatch中thorw如果不处理错误,则生成器会被关闭
    // } catch (err) {
    //   console.log(err);
    // }
    // console.log(b.next());//value:undefined done:false 生成器被关闭

    //注意,必须先执行生成器函数,否则yield捕获不到错误,相当于在函数外部抛出错误 
    console.log(b.next());
    // b.throw('出错啦123')
    console.log(b.throw('出错啦123'));//出错啦!! value:3 done:false  生成器.throw返回生成器对象
    console.log(b.next());//内部的trycatch块不会关闭生成器
  </script>
</body>
</html>